name: vanguard
description: Vanguard Latest App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  equatable: ^2.0.0
  http: ^0.13.1
  dartz: ^0.10.0-nullsafety.1
  get_it: ^6.1.1
  dio: ^4.0.6
  google_fonts: ^2.0.0
  flutter_bloc: ^7.0.0
  flutter_secure_storage: ^7.0.1
  flutter_svg: ^1.1.6
  connectivity_plus: ^2.3.0
  cached_network_image: ^3.0.0
  hive: ^2.0.4
  shimmer: ^2.0.0
  timeago: ^3.3.0
  liquid_pull_to_refresh: ^3.0.1
  internet_connection_checker: ^0.0.1+4
  intl: ^0.17.0
  json_annotation: ^4.7.0
  persistent_bottom_nav_bar: ^5.0.2
  pretty_dio_logger: ^1.1.1
  path_provider: ^2.0.1
  html: ^0.15.1
  youtube_player_flutter: ^8.0.0
  share_plus: ^6.3.1
  url_launcher: ^6.1.9
  font_awesome_flutter: ^10.4.0
  flare_flutter: ^3.0.0
  webview_flutter: ^4.0.4
  flutter_localizations:
    sdk: flutter
  salomon_bottom_bar: ^3.3.1
  flutter_screenutil: ^5.7.0

dev_dependencies:
  hive_generator: ^1.1.0
  build_runner: ^2.0.1
  test: ^1.16.5
  bloc_test: ^8.0.0
  mockito: ^5.0.5
  json_serializable: ^6.5.4
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/pngs/
    - assets/icons/
    - assets/languages/
    - assets/animations/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
